# Generated by Django 5.0.7 on 2024-08-14 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='telegram_id',
        ),
    ]
