# Generated by Django 5.0.7 on 2024-08-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_feedback_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='is_read',
        ),
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('NEW', 'new'), ('READ', 'read'), ('CANCEL', 'Cancel')], default='NEW', max_length=9),
        ),
    ]
