# Generated by Django 5.0.7 on 2024-08-20 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_alter_feedback_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='craeted_at',
            new_name='created_at',
        ),
    ]
