# Generated by Django 5.0.7 on 2024-08-20 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_rename_craeted_at_feedback_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='created_at',
            new_name='craeted_at',
        ),
    ]
